interface/build_city.c File Reference
#include <stdio.h>
#include <err.h>
#include <stdlib.h>
#include `toSDL.h`
#include `../metro/network.h`
Functions
char ** genMat (int DIM)
A tool to test build_city.
void build_city (char **matrice, int DIM)
Displays with SDL, the city as well as the subway lines and stations.
Detailed Description
This file was mainly used for tests and built a random city in order to test the display with our GTK and SDL Graphical User Interface
Author
Remy Decourcelle remy.decoutcelle@epita.fr, Loïck Balloy loick.balloy@epita.fr, Axel Cochepin axel.cochepin@epita.fr, Guillaume Charvolin guillaume.charvolin@epita.fr
Version
0.1
Date
2022
Function Documentation
build_city()
void build_city (char ** matrice, int DIM)
{
  PrintMat(matrice, DIM); // Uses SDL to display a given matrix
  struct EDGE *edges = MakeMetro(matrice, DIM); // Executes the subway algorithm
  PrintMetro(edges, DIM); // Uses SDL to display a graph of the subway lines and stations
  for(int i = 0; i < DIM; i++)
    {
      free(matrice[i]);
    }
  free(matrice);
  free(edges);
}
References MakeMetro(), PrintMat(), and PrintMetro().
Referenced by main(), and on_click_button().
genMat()
char ** genMat (int DIM)
{
  char **matrice;
  matrice = malloc(sizeof(char *)* DIM);
  for(int k = 0; k < DIM; k++)
    {
      matrice[k] = malloc(sizeof(char *) * DIM);
    }
  for(int i = 0; i < DIM; i++)
    {
      for(int j =0; j < DIM; j++)
    {
            int number = rand();
            if(number%2 == 0)
          matrice[i][j] = '1';
        if(number%2 != 0)
          matrice[i][j] = '4';
            if(number%3 == 0)
          matrice[i][j] = '2';
            if(number%5 == 0)
          matrice[i][j] = '3';
        if(number%7 == 0)
          matrice[i][j] = '4';
        if(number%11 == 0)
          matrice[i][j] = '0';
    }
    }
  return matrice;
}
Referenced by main().