metro/graph.c File Reference
#include <stdio.h>
#include <stdlib.h>
#include `graph.h`
Functions
Graph new_graph (int vertices, Bool is_oriented)
Bool is_empty_graph (Graph g)
NodeList add_node (int x)
void add_edge (Graph g, int src, int dest)
void add_label (Graph g, int num, int i, int j)
void print_graph (Graph g)
void display_graph (Graph g)
void erase_graph (Graph g)
Detailed Description
This files creates and displays a graph (mainly used for tests).
Author
Remy Decourcelle remy.decoutcelle@epita.fr, Loïck Balloy loick.balloy@epita.fr, Axel Cochepin axel.cochepin@epita.fr, Guillaume Charvolin guillaume.charvolin@epita.fr
Version
0.1
Date
2022
Function Documentation
add_edge()
void add_edge (Graph g, int src, int dest)
Ajoute une arête à un Graphe
Parameters
g Le Graphe
src Le premier sommet (ou source)
dest Le second sommet (ou destination)
{
    NodeList n = add_node(dest);
    n->next = g->tab_neighbours[src-1].begin;
    g->tab_neighbours[src-1].begin = n;
    if(!g->is_oriented)
    {
        n = add_node(src);
        n->next = g->tab_neighbours[dest-1].begin;
        g->tab_neighbours[dest-1].begin = n;
    }
    //Ajout d'un lien dans le fichier Graphviz
    if(g->is_oriented)
        fprintf(g->graph_file, "\t%d -> %d;\n", src, dest);
    else
        fprintf(g->graph_file, "\t%d -- %d;\n", src, dest);
}
References add_node(), AdjencyListElement::begin, GraphElement::graph_file, GraphElement::is_oriented, NodeListElement::next, and GraphElement::tab_neighbours.
Referenced by buildAdjlists(), buildAdjlists2(), and main().
add_label()
void add_label (Graph g, int num, int i, int j)
{
  fprintf(g->graph_file, "\t%d [label=\"(%d,%d)\"]; \n", num, i, j);
}
References GraphElement::graph_file.
Referenced by BuildStations().
add_node()
NodeList add_node (int x)
Retourne un Noeud
Parameters
x La valeur du Noeud
Le Noeud créé
{
    NodeList n = malloc(sizeof(NodeListElement));
    if(n == NULL)
    {
        fprintf(stderr, "Erreur : Probleme creation Node.\n");
        exit(EXIT_FAILURE);
    }
    n->value = x;
    n->next = NULL;
    return n;
}
References NodeListElement::next, and NodeListElement::value.
Referenced by add_edge().
display_graph()
void display_graph (Graph g)
Affiche un Graphe en 2D (avec Graphviz sous WINDOWS)
Parameters
g Le Graphe
{
    //Windows seulement !
    if(g->is_oriented)
        system("dot -Tpng digraph.out -o graph.png");
    else
        system("dot -Tpng graph.out -o graph.png");
}
References GraphElement::is_oriented.
Referenced by main(), and MakeMetro().
erase_graph()
void erase_graph (Graph g)
Supprime un Graphe
Parameters
g Le Graphe
{
    if(is_empty_graph(g))
    {
        printf("Rien a effacer, le Graphe n'existe pas.\n");
        return;
    }
    //Si il existe des sommets adjacents
    if(g->tab_neighbours)
    {
        int i;
        for(i = 1 ; i < g->nb_vertices + 1 ; i++)
        {
            NodeList n = g->tab_neighbours[i-1].begin;
            
            while(n != NULL)
            {
                NodeList tmp = n;
                n = n->next;
                free(tmp);
            }
        }
        //Libération de la liste d'adjacence
        free(g->tab_neighbours);
    }
    //Fin et fermeture du fichier Graphviz
    fprintf(g->graph_file, "}\n");
    fclose(g->graph_file);
    //Libération du Graphe de la mémoire
    free(g);
}
References AdjencyListElement::begin, GraphElement::graph_file, is_empty_graph(), GraphElement::nb_vertices, NodeListElement::next, and GraphElement::tab_neighbours.
Referenced by main(), and MakeMetro().
is_empty_graph()
Bool is_empty_graph (Graph g)
Teste si un Graphe existe
Parameters
g Le Graphe à vérifier
Returns
true Si le Graphe n'existe pas, false sinon
{
    if(g == NULL)
        return true;
    return false;
}
Referenced by erase_graph().
new_graph()
Graph new_graph (int vertices, Bool is_oriented)
Créée un Graphe
Parameters
vertices Le nombre de sommets
is_oriented Est-ce un graphe orienté ou non-orienté ?
Returns
Le graphe créé
{
    int i;
    GraphElement *element;
    element = malloc(sizeof(*element));
    if(element == NULL)
    {
        fprintf(stderr, "Erreur : Probleme creation Graphe.\n");
        exit(EXIT_FAILURE);
    }
    element->is_oriented = is_oriented;
    element->nb_vertices = vertices;
    element->tab_neighbours = malloc(vertices * sizeof(AdjencyListElement));
    if(element->tab_neighbours == NULL)
    {
        fprintf(stderr, "Erreur : Probleme creation Graphe.\n");
        exit(EXIT_FAILURE);
    }
    for(i = 1 ; i < element->nb_vertices + 1 ; i++)
        element->tab_neighbours[i-1].begin = NULL;
    if(element->is_oriented)
        element->graph_file = fopen("digraph.out", "w");
    else
        element->graph_file = fopen("graph.out", "w");
    if(element->graph_file == NULL)
    {
        fprintf(stderr, "Erreur : Probleme creation du fichier.\n");
        exit(EXIT_FAILURE);
    }
    if(element->is_oriented)
        fprintf(element->graph_file, "digraph my_graph\n{\n");
    else
        fprintf(element->graph_file, "graph my_graph\n{\n");
    return element;
}
References AdjencyListElement::begin, GraphElement::graph_file, GraphElement::is_oriented, GraphElement::nb_vertices, and GraphElement::tab_neighbours.
Referenced by main(), and MakeMetro().
print_graph()
void print_graph (Graph g)
Affiche un Graphe en mode console
Parameters
g Le Graphe
{
    int i;
    for(i = 1 ; i < g->nb_vertices + 1 ; i++)
    {
        NodeList n = g->tab_neighbours[i-1].begin;
        printf("(%d) : ", i);
        while(n != NULL)
        {
            printf("%d, ", n->value);
            n = n->next;
        }
        printf("NULL\n");
    }
}
References AdjencyListElement::begin, GraphElement::nb_vertices, NodeListElement::next, GraphElement::tab_neighbours, and NodeListElement::value.
Referenced by main(), and MakeMetro().