loader/loadtools.c File Reference
#include `loadtools.h`
#include <stdlib.h>
#include <stdio.h>
Functions
FILE * settings_open ()
void print_value (int **building_value)
void print_labels (char **building_labels)
void print_bias (int *building_bias, char jump)
char isBias (char *line)
char isHabitant (char *line)
void free_building_list (void **build_)
Variables
int BUILDING_NUMBER_TYPE = 8
int VALUE_NUMBER_TYPE = 8
int BIAS_NUMBER = 6
int BUFFER_SIZE = 32
int LINE_BUFFER_SIZE = 256
int LABEL_SIZE = 3
char SETTINGS [] = `settings`
Function Documentation
free_building_list()
void free_building_list (void ** build_)
{
    for (int i = 0; i < BUILDING_NUMBER_TYPE; ++i)
        free(*(build_ + i));
    free(build_);
}
References BUILDING_NUMBER_TYPE.
Referenced by createWay(), and testAssign().
isBias()
char isBias (char * line)
{
    char is = 0;
    if (*line == 'B' && *(line + 1) == 'I' && *(line + 2) == 'A')
        is = 1;
    return is;
}
Referenced by load_building_bias(), and write_bias().
isHabitant()
char isHabitant (char * line)
{
    char is = 0;
    if (*line == 'H' && *(line + 1) == 'A' && *(line + 2) == 'B')
        is = 1;
    return is;
}
Referenced by load_habitant_number(), and write_habitant_number().
print_bias()
void print_bias (int * building_bias, char jump)
{
    printf("bias = [");
    for (int i = 0; i < BIAS_NUMBER; ++i)
    {
        if (i == BIAS_NUMBER - 1)
            printf("%i]\n", *(building_bias + i));
        else
            printf("%i, ", *(building_bias + i));
    }
    if (jump)
        printf("\n");
}
References BIAS_NUMBER.
print_labels()
void print_labels (char ** building_labels)
{
    printf("labels = [");
    for (int i = 0; i < BUILDING_NUMBER_TYPE; ++i)
    {
        if (i == BUILDING_NUMBER_TYPE - 1)
            printf("%s]\n", *(building_labels + i));
        else
            printf("%s, ", *(building_labels + i));
    }
    printf("\n");
}
References BUILDING_NUMBER_TYPE.
print_value()
void print_value (int ** building_value)
{
    for (int i = 0; i < BUILDING_NUMBER_TYPE; ++i)
    {
        printf("building %i = [", i);
        for (int j = 0; j < VALUE_NUMBER_TYPE; ++j)
        {
            if (j == VALUE_NUMBER_TYPE - 1)
                printf("%i", *(j + *(building_value + i)));
            else
                printf("%i, ", *(j + *(building_value + i)));
        }
        printf("]\n");
    }
    printf("\n");
}
References BUILDING_NUMBER_TYPE, and VALUE_NUMBER_TYPE.
settings_open()
FILE * settings_open ()
{
    FILE *file = fopen(SETTINGS, "r+");
    if (file == NULL)
    {
        perror("Error in settings_open_write() in load");
        exit(1);
    }
    return file;
}
References SETTINGS.
Referenced by load_building_bias(), load_building_labels(), load_building_value(), load_habitant_number(), write_bias(), and write_habitant_number().
Variable Documentation
BIAS_NUMBER
int BIAS_NUMBER = 6
Referenced by init_building_bias(), print_bias(), and write_bias().
BUFFER_SIZE
int BUFFER_SIZE = 32
Referenced by fill_value().
BUILDING_NUMBER_TYPE
int BUILDING_NUMBER_TYPE = 8
Referenced by free_building_list(), init_building_labels(), init_building_value(), load_building_labels(), load_building_value(), print_labels(), and print_value().
LABEL_SIZE
int LABEL_SIZE = 3
Referenced by fill_label(), and init_building_labels().
LINE_BUFFER_SIZE
int LINE_BUFFER_SIZE = 256
Referenced by load_building_bias(), load_building_labels(), load_building_value(), load_habitant_number(), write_bias(), and write_habitant_number().
SETTINGS
char SETTINGS[] = `settings`
Referenced by settings_open().
VALUE_NUMBER_TYPE
int VALUE_NUMBER_TYPE = 8
Referenced by init_building_value(), and print_value().