metro/metro.c File Reference
#include <stdio.h>
#include <stdlib.h>
#include `graph.h`
Functions
int main (void)
Detailed Description
This file contains our metro algorithm.
Author
Remy Decourcelle remy.decoutcelle@epita.fr, Loïck Balloy loick.balloy@epita.fr, Axel Cochepin axel.cochepin@epita.fr, Guillaume Charvolin guillaume.charvolin@epita.fr
Version
0.1
Date
2022
Function Documentation
main()
int main (void)
{
    Graph g1 = new_graph(5, false);
    add_edge(g1, 1, 2);
    add_edge(g1, 1, 5);
    add_edge(g1, 2, 4);
    add_edge(g1, 2, 3);
    add_edge(g1, 3, 4);
    add_edge(g1, 4, 5);
    add_edge(g1, 1, 4);
    print_graph(g1);
    display_graph(g1);
    erase_graph(g1);
    system("dot -Tpng graph.out -o graph.png");
    return 0;
}
References add_edge(), display_graph(), erase_graph(), new_graph(), and print_graph().