banker/need.c File Reference
#include `../loader/read.h`
#include `../loader/write.h`
#include `need.h`
#include `building.h`
#include <err.h>
#include <stdlib.h>
#include <stdio.h>
Functions
int * initTownList3 (unsigned int nb_hab, double sec)
Variables
int NO = 0
int YES = 1
unsigned char NUMBER_TYPE = 7
int HALL [] = {0, 10, 50, 0, 0, 10, 30}
int PROPERTY [] = {0, 40, -60, 35, 20, 10, 15}
int OFFICE [] = {0, -60, 50, 10, 0, 0, 10}
int COMISSARY [] = {0, -20, 20, 0, 0, -70, 20}
int SHOP [] = {0, -10, 20, -60, 0, 10, 10}
int HOSPITAL [] = {0, -20, 30, 0, -70, 0, 20}
int SUBWAY [] = {0, 10, 10, 10, 10, 10, 20}
Function Documentation
initTownList3()
int * initTownList3 (unsigned int nb_hab, double sec)
{
  //int comi_range = 60000;
  //int hosp_range = 20000;
  sec +=0;
  int *bat = malloc(sizeof(int)* NUMBER_TYPE);
  int **building_value = load_building_value();
  int *bias = load_building_bias();
  for (int x = 0; x < 7; x++)
  {
      *(bat + x) = nb_hab / *((*(building_value + x)) + 7);
      if (x == 6 && *(bat + x) == 1)
          *(bat + x) = 0;
      else if (*(bat + x) == 0)
          *(bat + x) = 1;
  }
  *(bat + 1) += *(bat + 1) * (*(bias + 2)) / 100;
  *(bat + 2) += *(bat + 2) * (*(bias + 1)) / 100;
  *(bat + 3) += *(bat + 3) * (*(bias + 5)) / 100;
  *(bat + 4) += *(bat + 4) * (*(bias + 3)) / 100;
  *(bat + 5) += *(bat + 5) * (*(bias + 4)) / 100;
  return bat;
}
References load_building_bias(), load_building_value(), and NUMBER_TYPE.
Referenced by testAssign().
Variable Documentation
COMISSARY
int COMISSARY[] = {0, -20, 20, 0, 0, -70, 20}
HALL
int HALL[] = {0, 10, 50, 0, 0, 10, 30}
HOSPITAL
int HOSPITAL[] = {0, -20, 30, 0, -70, 0, 20}
NO
int NO = 0
NUMBER_TYPE
unsigned char NUMBER_TYPE = 7
Referenced by initTownList3().
OFFICE
int OFFICE[] = {0, -60, 50, 10, 0, 0, 10}
PROPERTY
int PROPERTY[] = {0, 40, -60, 35, 20, 10, 15}
SHOP
int SHOP[] = {0, -10, 20, -60, 0, 10, 10}
SUBWAY
int SUBWAY[] = {0, 10, 10, 10, 10, 10, 20}
YES
int YES = 1