banker/need.h File Reference
Functions
int * initTownList3 (unsigned int nb_hab, double sec)
We create a list of int where the index represents a building type and the value is the number of buildings left to place, this list is defined with the settings file.
Function Documentation
initTownList3()
int * initTownList3 (unsigned int nb_hab, double sec)
{
  //int comi_range = 60000;
  //int hosp_range = 20000;
  sec +=0;
  int *bat = malloc(sizeof(int)* NUMBER_TYPE);
  int **building_value = load_building_value();
  int *bias = load_building_bias();
  for (int x = 0; x < 7; x++)
  {
      *(bat + x) = nb_hab / *((*(building_value + x)) + 7);
      if (x == 6 && *(bat + x) == 1)
          *(bat + x) = 0;
      else if (*(bat + x) == 0)
          *(bat + x) = 1;
  }
  *(bat + 1) += *(bat + 1) * (*(bias + 2)) / 100;
  *(bat + 2) += *(bat + 2) * (*(bias + 1)) / 100;
  *(bat + 3) += *(bat + 3) * (*(bias + 5)) / 100;
  *(bat + 4) += *(bat + 4) * (*(bias + 3)) / 100;
  *(bat + 5) += *(bat + 5) * (*(bias + 4)) / 100;
  return bat;
}
References load_building_bias(), load_building_value(), and NUMBER_TYPE.
Referenced by testAssign().