metro/network.h File Reference
#include <stdlib.h>
Data Structures
struct EDGE
Functions
struct EDGE * MakeMetro (char **matrice, int DIM)
Function Documentation
MakeMetro()
struct EDGE * MakeMetro (char ** matrice, int DIM)
{
  int NUMBER_STATIONS;
  double MAX = 4.2;
  NUMBER_STATIONS = nb_stations(matrice, DIM);
  Graph g1 = new_graph(NUMBER_STATIONS, false);
  fprintf(g1->graph_file, "\tedge [color=black];\n");
  fprintf(g1->graph_file, "\tnode [color=turquoise, style=filled];\n");
  struct Metro *STATIONS = BuildStations(matrice, DIM, g1);
  
  struct EDGE *edges = buildAdjlists2(STATIONS, NUMBER_STATIONS, MAX, g1);
  print_graph(g1);
  display_graph(g1);
  erase_graph(g1);
  system("dot -Tpng graph.out -o graph.png");
  
  free(STATIONS);
  return edges;
}
References buildAdjlists2(), BuildStations(), display_graph(), erase_graph(), GraphElement::graph_file, nb_stations(), new_graph(), and print_graph().
Referenced by build_city().