interface/tool/pixel_operations.c File Reference
#include <err.h>
#include `pixel_operations.h`
Functions
static Uint8 * pixel_ref (SDL_Surface *surf, unsigned x, unsigned y)
Uint32 get_pixel (SDL_Surface *surface, unsigned x, unsigned y)
void put_pixel (SDL_Surface *surface, unsigned x, unsigned y, Uint32 pixel)
void update_surface (SDL_Surface *screen, SDL_Surface *image)
Function Documentation
get_pixel()
Uint32 get_pixel (SDL_Surface * surface, unsigned x, unsigned y)
{
    Uint8 *p = pixel_ref(surface, x, y);
    switch (surface->format->BytesPerPixel)
    {
        case 1:
            return *p;
        case 2:
            return *(Uint16 *)p;
        case 3:
            if (SDL_BYTEORDER == SDL_BIG_ENDIAN)
                return p[0] << 16 | p[1] << 8 | p[2];
            else
                return p[0] | p[1] << 8 | p[2] << 16;
        case 4:
            return *(Uint32 *)p;
    }
    return 0;
}
References pixel_ref().
pixel_ref()
static Uint8 * pixel_ref (SDL_Surface * surf, unsigned x, unsigned y) [static]
{
    int bpp = surf->format->BytesPerPixel;
    return (Uint8*)surf->pixels + y * surf->pitch + x * bpp;
}
Referenced by get_pixel(), and put_pixel().
put_pixel()
void put_pixel (SDL_Surface * surface, unsigned x, unsigned y, Uint32 pixel)
{
    Uint8 *p = pixel_ref(surface, x, y);
    switch(surface->format->BytesPerPixel)
    {
        case 1:
            *p = pixel;
            break;
        case 2:
            *(Uint16 *)p = pixel;
            break;
        case 3:
            if(SDL_BYTEORDER == SDL_BIG_ENDIAN)
            {
                p[0] = (pixel >> 16) & 0xff;
                p[1] = (pixel >> 8) & 0xff;
                p[2] = pixel & 0xff;
            }
            else
            {
                p[0] = pixel & 0xff;
                p[1] = (pixel >> 8) & 0xff;
                p[2] = (pixel >> 16) & 0xff;
            }
            break;
        case 4:
            *(Uint32 *)p = pixel;
            break;
    }
}
References pixel_ref().
update_surface()
void update_surface (SDL_Surface * screen, SDL_Surface * image)
{
    if (SDL_BlitSurface(image, NULL, screen, NULL) < 0)
        warnx("BlitSurface error: %s\n", SDL_GetError());
    SDL_UpdateRect(screen, 0, 0, image->w, image->h);
}