interface/tool/tool_image.c File Reference
#include `stdio.h`
#include `SDL/SDL.h`
#include `SDL/SDL_image.h`
#include `pixel_operations.h`
#include `err.h`
Functions
void init_sdl ()
SDL_Surface * load_image (char *path)
SDL_Surface * create_image (size_t h, size_t d)
SDL_Surface * display_image (SDL_Surface *img)
void wait_for_keypressed ()
Function Documentation
create_image()
SDL_Surface * create_image (size_t h, size_t d)
{
        SDL_Surface* img=NULL;
        img = SDL_CreateRGBSurface(0, h, d,32,0,0,0,0);
        return img;
}
display_image()
SDL_Surface * display_image (SDL_Surface * img)
{
    SDL_Surface *screen;
    // Set the window to the same size as the image
    screen = SDL_SetVideoMode(img->w, img->h, 0, SDL_SWSURFACE|SDL_ANYFORMAT);
    if (screen == NULL)
    {
        // error management
        errx(1, "Couldn't set %dx%d video mode: %s\n",
                img->w, img->h, SDL_GetError());
    }
    // Blit onto the screen surface
    if(SDL_BlitSurface(img, NULL, screen, NULL) < 0)
        warnx("BlitSurface error: %s\n", SDL_GetError());
    // Update the screen
    SDL_UpdateRect(screen, 0, 0, img->w, img->h);
    // return the screen for further uses
    return screen;
}
init_sdl()
void init_sdl ()
{
    // Init only the video part.
    // If it fails, die with an error message.
    if(SDL_Init(SDL_INIT_VIDEO) == -1)
        errx(1,"Could not initialize SDL: %s.\n", SDL_GetError());
}
Referenced by PrintMat(), and PrintMetro().
load_image()
SDL_Surface * load_image (char * path)
{
    SDL_Surface* img;
    // Load an image using SDL_image with format detection.
    // If it fails, die with an error message.
    img = IMG_Load(path);
    if (!img)
        errx(3, "can't load %s: %s", path, IMG_GetError());
    return img;
}
Referenced by PrintMat(), and PrintMetro().
wait_for_keypressed()
void wait_for_keypressed ()
{
    SDL_Event event;
    // Wait for a key to be down.
    do
    {
        SDL_PollEvent(&event);
    } while(event.type != SDL_KEYDOWN);
    printf("%i",SDLK_f);
    // Wait for a key to be up.
    do
    {
        SDL_PollEvent(&event);
    } while(event.type != SDL_KEYUP);
}