geographer/update.c File Reference
#include `../assign/assign_tools.h`
#include `err.h`
#include `update.h`
#include <stdio.h>
Functions
int ponderation (int x, int y, int val, int a, int b)
This functions computes a value to change the needs according to a distance from a cell.
void attribuate (int x, int y, struct cell *cell, int *value, int a, int b)
A tool to give a cell a value.
void reverseAttribuate (int x, int y, struct cell *cell, int *value, int a, int b)
The same as attribuate but reversed no further explaination will be provided.
char equation (int x, int y, int a, int b, int range)
Simple inequation that returns an int 0 or 1 casted to a char.
void updateAround (struct map *map, int a, int b, int **building_value)
Using ponderation we update the values around a cell placed at coordinates x and y.
void reverseUpdateAround (struct map *map, int a, int b, int **building_value)
The same as updateAround but reversed no further explaination will be provided.
Detailed Description
This files updates the needs to allow the propagation of our rules
Author
Remy Decourcelle remy.decoutcelle@epita.fr, Loïck Balloy loick.balloy@epita.fr, Axel Cochepin axel.cochepin@epita.fr, Guillaume Charvolin guillaume.charvolin@epita.fr
Version
0.1
Date
2022
Function Documentation
attribuate()
void attribuate (int x, int y, struct cell * cell, int * value, int a, int b)
{
    int *stats = cell->stats;
    for (int i = 0; i < NBSTATS; i++)
        *(stats + i) += ponderation(x, y, *(value + i), a, b);
}
References NBSTATS, ponderation(), and cell::stats.
Referenced by updateAround().
equation()
char equation (int x, int y, int a, int b, int range)
{
    return (x - a)*(x - a) + (y - b) * (y - b) < range * range;
}
Referenced by reverseUpdateAround(), and updateAround().
ponderation()
int ponderation (int x, int y, int val, int a, int b)
{
    int xtemp = x - a;
    int ytemp = y - b;
    xtemp = xtemp < 0?(-1)*xtemp:xtemp;
    ytemp = ytemp < 0?(-1)*ytemp:ytemp;
    if(xtemp+ytemp == 0)
      return 0;
    float pond = ((float)1/((float)(0.85+(float)xtemp/4+(float)ytemp/4)));//The bias we use in this function are represented pas the values 0.85 and /4
    int ponderation = (int)(pond*(float)val);
    return ponderation;
}
References ponderation().
Referenced by attribuate(), ponderation(), and reverseAttribuate().
reverseAttribuate()
void reverseAttribuate (int x, int y, struct cell * cell, int * value, int a, int b)
{
    int *stats = cell->stats;
    for (int i = 0; i < NBSTATS; i++)
        *(stats + i) -= ponderation(x, y, *(value + i), a, b);
}
References NBSTATS, ponderation(), and cell::stats.
Referenced by reverseUpdateAround().
reverseUpdateAround()
void reverseUpdateAround (struct map * map, int a, int b, int ** building_value)
{
    struct cell *cell = (map->cells) + (a + b * map->maxWidth);
    if (cell->type == -1)
        errx(1, "reverseUpdateAround : Error the cell is not occupied by a building");
    if (cell->type == 7)
        return;
    int type = cell->type;
    int *value = *(building_value + type);
    int range = *(value + 6);
    int xsquare = a - range;
    int ysquare = b - range;
    int diam = range * 2;
    struct cell *cellatt;
    for (int x = xsquare; x < (xsquare + diam); ++x)
        if (x >= 0 && x < map->maxWidth)
            for (int y = ysquare; y < (ysquare + diam); ++y)
                if (y >= 0 && y < map->maxHeight)
                    if (equation(x, y, a, b, range))
                        {
                            cellatt = (map->cells) + (x + y * map->maxWidth);
                            reverseAttribuate(x, y, cellatt, value, a, b);
                        }
}
References map::cells, equation(), map::maxWidth, reverseAttribuate(), and cell::type.
Referenced by createWay(), and replaceTown().
updateAround()
void updateAround (struct map * map, int a, int b, int ** building_value)
{
    struct cell *cell = (map->cells) + (a + b * map->maxWidth);
    if (cell->type == -1)
        errx(1, "updateAround : Error the cell is not occupied by a building at %i, %i \n ",a,b);
    int type = cell->type;
    int *value = *(building_value + type);
    int range = *(value + 6);
    int xsquare = a - range;
    int ysquare = b - range;
    int diam = range * 2;
    struct cell *cellatt;
    for (int x = xsquare; x < (xsquare + diam); ++x)
        if (x >= 0 && x < map->maxWidth)
            for (int y = ysquare; y < (ysquare + diam); ++y)
                if (y >= 0 && y < map->maxHeight)
                    if (equation(x, y, a, b, range))
                        {
                            cellatt = (map->cells) + (x + y * map->maxWidth);
                            attribuate(x, y, cellatt, value, a, b);
                        }
}
References attribuate(), map::cells, equation(), map::maxWidth, and cell::type.
Referenced by fillTown(), generateRandomSubway(), replaceTown(), and testAssign().