loader/write.c File Reference
#include <stdio.h>
#include <string.h>
#include `read.h`
#include `loadtools.h`
Functions
void write_habitant_number (int habitant_number)
void write_bias (int *building_bias)
Detailed Description
This file modifies the setting files to allow the modification of biases and rules in general.
Author
Remy Decourcelle remy.decoutcelle@epita.fr, Loïck Balloy loick.balloy@epita.fr, Axel Cochepin axel.cochepin@epita.fr, Guillaume Charvolin guillaume.charvolin@epita.fr
Version
0.1
Date
2022
Function Documentation
write_bias()
void write_bias (int * building_bias)
{
    FILE *file = settings_open();
    char buffer[LINE_BUFFER_SIZE];
    fgets(buffer, LINE_BUFFER_SIZE, file);
    long int ft = 0;
    long int lineS = 0;
    long int temp = 0;
    while(!isBias(buffer))
    {
        fgets(buffer, LINE_BUFFER_SIZE, file);
        temp = ftell(file);
        lineS = ft - temp;
        ft = temp;
    }
    fseek(file, lineS, SEEK_CUR);
    char dst[LINE_BUFFER_SIZE];
    char src[LINE_BUFFER_SIZE];
    strcpy(dst, "BIAS = [");
    for (int i = 0; i < BIAS_NUMBER; ++i)
    {
        if (i == BIAS_NUMBER - 1)
            sprintf(src, "%i] ", *(building_bias + i));
        else
            sprintf(src, "%i, ", *(building_bias + i));
        strcat(dst, src);
    }
    fprintf(file, "%s", dst);
    fclose(file);
}
References BIAS_NUMBER, isBias(), LINE_BUFFER_SIZE, and settings_open().
Referenced by on_click_button().
write_habitant_number()
void write_habitant_number (int habitant_number)
{
    FILE *file = settings_open();
    char buffer[LINE_BUFFER_SIZE];
    fgets(buffer, LINE_BUFFER_SIZE, file);
    long int ft = 0;
    long int lineS = 0;
    long int temp = 0;
    while(!isHabitant(buffer))
    {
        fgets(buffer, LINE_BUFFER_SIZE, file);
        temp = ftell(file);
        lineS = ft - temp;
        ft = temp;
    }
    fseek(file, lineS, SEEK_CUR);
    char toPrint[LINE_BUFFER_SIZE];
    sprintf(toPrint, "HABITANT_NUMBER = [%i] ", habitant_number);
    fprintf(file, "%s", toPrint);
    fclose(file);
}
References isHabitant(), LINE_BUFFER_SIZE, and settings_open().